import { useMemo, useState, type ReactNode } from "react";
import { CAGI_UP6S, COPEL_A4_TARIFFS, HP_ROWS, INGERSOLL_FAMILIES, TECH_SOURCES, VARIABLE_SPEED_MODELS, VERIFIED_MODELS } from "@/lib/diagnostic-data";

const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});
const fmt=(v:number,d=1)=>v.toLocaleString("pt-BR",{maximumFractionDigits:d,minimumFractionDigits:d});
const Source=({links}:{links:{label:string;url:string}[]})=><details className="v2-source"><summary>Como este diagnóstico é calculado</summary>{links.map(x=><a key={x.url} href={x.url} target="_blank" rel="noreferrer">{x.label}</a>)}</details>;
const Field=({label,children}:{label:string;children:ReactNode})=><label className="v2-diagnostic-field">{label}{children}</label>;

export function TariffReferencePanel(){
 return <div className="v2-evidence-panel"><div><span className="v2-kicker">REFERÊNCIA FINANCEIRA FIXA</span><h3>Tarifa não é um slider.</h3><p>Os cálculos de energia usam a Tarifa de Aplicação da COPEL-DIS homologada pela ANEEL para o subgrupo A4, vigência 24/06/2026 a 23/06/2027. O valor é a soma TE + TUSD de energia e serve como referência técnica comparativa, não como reprodução da fatura.</p></div><div className="v2-tariff-grid">{COPEL_A4_TARIFFS.map(x=><article key={x.id}><small>{x.label}</small><strong>R$ {fmt(x.value,5)}<i>/kWh</i></strong><span>TUSD {fmt(x.tusd,2)} + TE {fmt(x.te,2)} R$/MWh</span></article>)}</div><div className="v2-evidence-foot"><b>Não incluído:</b> demanda contratada/medida, ultrapassagem, impostos, bandeiras e demais componentes da fatura. <a href={TECH_SOURCES.copel.url} target="_blank" rel="noreferrer">Copel</a><a href={TECH_SOURCES.aneel.url} target="_blank" rel="noreferrer">Base ANEEL</a></div></div>
}

export function CompressorAnnualTool(){
 const [modelId,setModelId]=useState("up6s-30-125"),[hours,setHours]=useState(4000),[tariffId,setTariffId]=useState("a4-offpeak");
 const m=CAGI_UP6S.find(x=>x.id===modelId)??CAGI_UP6S[4],t=COPEL_A4_TARIFFS.find(x=>x.id===tariffId)??COPEL_A4_TARIFFS[0];
 const kwh=(m.packageKw??0)*hours,cost=kwh*t.value;
 return <div className="v2-diagnostic-calc v2-diagnostic-calc-featured"><div className="v2-calc-head"><div><span>01 · INGERSOLL RAND</span><h3>Consumo anual por modelo medido</h3></div><strong>{money(cost)}<small> referência anual</small></strong></div><p>Selecionamos apenas modelos que possuem ficha CAGI da Ingersoll Rand com potência total do pacote em plena carga. HP sozinho não é usado para estimar consumo.</p><div className="v2-calc-fields"><Field label="Modelo"><select value={modelId} onChange={e=>setModelId(e.target.value)}>{CAGI_UP6S.map(x=><option key={x.id} value={x.id}>{x.model}</option>)}</select></Field><Field label="Horas reais no ano"><input type="number" min="1" max="8760" value={hours} onChange={e=>setHours(Math.min(8760,Math.max(0,Number(e.target.value)||0)))}/></Field><Field label="Tarifa oficial de referência"><select value={tariffId} onChange={e=>setTariffId(e.target.value)}>{COPEL_A4_TARIFFS.map(x=><option key={x.id} value={x.id}>{x.label} · R$ {x.value.toFixed(5)}/kWh</option>)}</select></Field></div><div className="v2-result-strip"><div><small>Entrada total CAGI</small><b>{fmt(m.packageKw??0,2)} kW</b></div><div><small>Vazão medida</small><b>{fmt(m.flowCfm,0)} cfm</b></div><div><small>Energia anual</small><b>{fmt(kwh,0)} kWh</b></div><div><small>Potência específica</small><b>{fmt(m.specificKw100Cfm??0,2)} kW/100 cfm</b></div></div><Source links={[{label:m.sourceLabel,url:m.sourceUrl},TECH_SOURCES.irCagi,TECH_SOURCES.copel,TECH_SOURCES.aneel]}/></div>
}

export function VerifiedCompressorTable(){
 const [family,setFamily]=useState("Todos");const families=["Todos",...Array.from(new Set(VERIFIED_MODELS.map(x=>x.family)))];const rows=VERIFIED_MODELS.filter(x=>family==="Todos"||x.family===family);
 return <div className="v2-data-card"><div className="v2-data-card-head"><div><span className="v2-kicker">BASE DE MODELOS VERIFICADA</span><h3>Especificações que entram no site somente com fonte.</h3><p>O catálogo abaixo separa a família comercial da medição energética. Onde a fonte não publica potência total do pacote, o site não calcula custo anual.</p></div><select value={family} onChange={e=>setFamily(e.target.value)}>{families.map(x=><option key={x}>{x}</option>)}</select></div><div className="v2-family-band"><b>Famílias atuais localizadas no catálogo oficial</b><div>{INGERSOLL_FAMILIES.map((x,i)=><span key={x.name+x.range+i}>{x.name}<i>{x.range}</i></span>)}</div><p>Esta faixa é um mapa de famílias do catálogo oficial, não uma promessa de disponibilidade local. O cálculo anual abaixo só é liberado para configurações com dados CAGI de potência total.</p></div><div className="v2-variable-catalog"><div className="v2-variable-catalog-head"><b>Todos os modelos de velocidade variável por faixa</b><span>Lista comercial organizada por família; pressão e disponibilidade dependem da configuração selecionada.</span></div>{VARIABLE_SPEED_MODELS.map(group=><article key={group.range}><div><strong>{group.range}</strong><small>{group.pressureRange}</small></div><p>{group.models.map(model=><b key={model}>{model}</b>)}</p><a href={group.sourceUrl} target="_blank" rel="noreferrer">fonte oficial</a></article>)}</div><div className="v2-tech-table-wrap"><table className="v2-tech-table"><thead><tr><th>Família</th><th>Modelo</th><th>HP</th><th>kW nominal</th><th>Pressão</th><th>FAD</th><th>Entrada pacote</th><th>Fonte</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.family}</td><td><b>{x.model}</b></td><td>{x.hp}</td><td>{x.nominalKw??"—"}</td><td>{fmt(x.pressureBar,1)} bar</td><td>{x.flowCfm} cfm</td><td>{x.packageKw?`${fmt(x.packageKw,2)} kW CAGI`:"não publicada nesta fonte"}</td><td><a href={x.sourceUrl} target="_blank" rel="noreferrer">abrir</a></td></tr>)}</tbody></table></div><div className="v2-evidence-foot">O catálogo oficial da Ingersoll Rand também lista linhas UP6, UP6S e Next Generation RS em faixas que vão de pequenas potências até centenas de kW. <a href="https://www.ingersollrand.com/en-us/products/air-compressors/oil-flooded-rotary-air-compressors/" target="_blank" rel="noreferrer">Catálogo oficial</a><a href="https://www.ingersollrand.com/api/air-compressor/cagi-data-sheets/contact-cooled-rotary" target="_blank" rel="noreferrer">Biblioteca CAGI</a></div></div>
}

export function HpKwReference(){return <div className="v2-diagnostic-calc"><div className="v2-calc-head"><div><span>02 · CONVERSÃO</span><h3>HP não é consumo elétrico.</h3></div></div><p>Esta tabela serve apenas para converter unidade de potência mecânica. O NIST define 1 horsepower (550 ft·lbf/s) = 745,6999 W. Um motor de 30 hp, portanto, não significa que um compressor consome exatamente 22,37 kW da rede.</p><div className="v2-mini-table">{HP_ROWS.map(x=><span key={x.hp}><b>{x.hp} hp</b><i>{fmt(x.kw,2)} kW</i></span>)}</div><Source links={[TECH_SOURCES.nist]}/></div>}

export function PressureSystemTool(){
 const [modelId,setModelId]=useState("up6s-30-125"),[current,setCurrent]=useState(8),[target,setTarget]=useState(7),[supply,setSupply]=useState(7.5),[point,setPoint]=useState(6.9),[liters,setLiters]=useState(1000),[p1,setP1]=useState(7),[p2,setP2]=useState(3.5),[seconds,setSeconds]=useState(120),[hours,setHours]=useState(4000),[tariffId,setTariffId]=useState("a4-offpeak");
 const m=CAGI_UP6S.find(x=>x.id===modelId)??CAGI_UP6S[4],t=COPEL_A4_TARIFFS.find(x=>x.id===tariffId)??COPEL_A4_TARIFFS[0];
 const deltaBar=Math.max(0,current-target),savingPct=deltaBar/0.1378952,savedKw=(m.packageKw??0)*(savingPct/100),annual=savedKw*hours*t.value;
 const networkDrop=Math.max(0,supply-point),networkPct=supply>0?networkDrop/supply*100:0;
 const volumeFt3=liters/28.3168466,minutes=Math.max(seconds/60,.0001),leakCfm=volumeFt3*Math.max(0,p1-p2)/(minutes*1.01325)*1.25,leakM3Min=leakCfm*.0283168466;
 return <div className="v2-diagnostic-calc v2-pressure-system"><div className="v2-calc-head"><div><span>03 · PRESSÃO E ESTANQUEIDADE</span><h3>Diagnóstico unificado do sistema pressurizado</h3></div><strong className={networkPct>=10?'is-risk':''}>{fmt(networkPct,1)}%<small> queda na rede</small></strong></div><p>Um único ensaio reúne a oportunidade de setpoint, a diferença entre a casa de máquinas e o ponto crítico e o teste de despressurização sem consumo produtivo.</p>
 <div className="v2-unified-test"><h4>01. Setpoint e energia</h4><div className="v2-calc-fields"><Field label="Modelo CAGI"><select value={modelId} onChange={e=>setModelId(e.target.value)}>{CAGI_UP6S.map(x=><option key={x.id} value={x.id}>{x.model}</option>)}</select></Field><Field label="Pressão atual (bar)"><input type="number" step="0.1" value={current} onChange={e=>setCurrent(Number(e.target.value)||0)}/></Field><Field label="Pressão alvo (bar)"><input type="number" step="0.1" value={target} onChange={e=>setTarget(Number(e.target.value)||0)}/></Field><Field label="Horas/ano"><input type="number" min="1" max="8760" value={hours} onChange={e=>setHours(Number(e.target.value)||0)}/></Field><Field label="Tarifa"><select value={tariffId} onChange={e=>setTariffId(e.target.value)}>{COPEL_A4_TARIFFS.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></Field></div><div className="v2-result-strip"><div><small>Redução avaliada</small><b>{fmt(deltaBar,2)} bar</b></div><div><small>Economia estimada</small><b>{fmt(savingPct,1)}%</b></div><div><small>Referência anual</small><b>{money(annual)}</b></div></div></div>
 <div className="v2-unified-test"><h4>02. Perda até o ponto de uso</h4><div className="v2-calc-fields"><Field label="Saída do reservatório (bar)"><input type="number" step="0.1" value={supply} onChange={e=>setSupply(Number(e.target.value)||0)}/></Field><Field label="Ponto crítico (bar)"><input type="number" step="0.1" value={point} onChange={e=>setPoint(Number(e.target.value)||0)}/></Field></div><div className={"v2-diagnostic-status "+(networkPct>=10?'risk':'ok')}><b>{networkPct>=10?'Acima da referência de triagem':'Abaixo de 10%, com espaço para otimização'}</b><span>Diferença: {fmt(networkDrop,2)} bar, equivalente a {fmt(networkPct,1)}% da pressão na origem.</span></div></div>
 <div className="v2-unified-test"><h4>03. Vazamento por despressurização</h4><div className="v2-calc-fields"><Field label="Volume pressurizado (litros)"><input type="number" min="1" value={liters} onChange={e=>setLiters(Number(e.target.value)||0)}/></Field><Field label="Pressão inicial (bar g)"><input type="number" step="0.1" value={p1} onChange={e=>setP1(Number(e.target.value)||0)}/></Field><Field label="Pressão final (bar g)"><input type="number" step="0.1" value={p2} onChange={e=>setP2(Number(e.target.value)||0)}/></Field><Field label="Tempo de queda (segundos)"><input type="number" min="1" value={seconds} onChange={e=>setSeconds(Number(e.target.value)||0)}/></Field></div><div className="v2-result-strip"><div><small>Vazamento estimado</small><b>{fmt(leakCfm,1)} cfm</b></div><div><small>Equivalente</small><b>{fmt(leakM3Min,2)} m³/min</b></div><div><small>Volume considerado</small><b>{fmt(liters,0)} litros</b></div></div></div>
 <p className="v2-tool-note">Referência de triagem: perto de 6,9 bar, uma redução de aproximadamente 0,14 bar na descarga corresponde a cerca de 1% de economia em plena vazão. A perda na distribuição deve ficar muito abaixo de 10%. O teste de estanqueidade exige planta sem consumo produtivo.</p><Source links={[TECH_SOURCES.doe,TECH_SOURCES.irOptimization,{label:m.sourceLabel,url:m.sourceUrl}]}/></div>
}

export function CycleLeakTool(){
 const [modelId,setModelId]=useState("up6s-30-125"),[load,setLoad]=useState(1),[off,setOff]=useState(4);const m=CAGI_UP6S.find(x=>x.id===modelId)??CAGI_UP6S[4],pct=(load+off)>0?load/(load+off)*100:0,cfm=m.flowCfm*pct/100;
 return <div className="v2-diagnostic-calc"><div className="v2-calc-head"><div><span>04 · CICLO CARGA/ALÍVIO</span><h3>Percentual de capacidade perdido em vazamento</h3></div><strong className={pct>10?'is-risk':''}>{fmt(pct,1)}%<small> da capacidade</small></strong></div><p>Para compressores com controle start/stop ou carga/alívio e nenhuma demanda produtiva, o DOE publica: vazamento (%) = T carga × 100 ÷ (T carga + t alívio).</p><div className="v2-calc-fields"><Field label="Modelo / capacidade"><select value={modelId} onChange={e=>setModelId(e.target.value)}>{CAGI_UP6S.map(x=><option key={x.id} value={x.id}>{x.model} · {x.flowCfm} cfm</option>)}</select></Field><Field label="Tempo em carga (min)"><input type="number" step="0.1" min="0" value={load} onChange={e=>setLoad(Number(e.target.value)||0)}/></Field><Field label="Tempo aliviado/desligado (min)"><input type="number" step="0.1" min="0" value={off} onChange={e=>setOff(Number(e.target.value)||0)}/></Field></div><div className="v2-result-strip"><div><small>Capacidade publicada</small><b>{m.flowCfm} cfm</b></div><div><small>Vazamento equivalente</small><b>{fmt(cfm,1)} cfm</b></div><div><small>Benchmark DOE</small><b>&lt;10%</b></div></div><p className="v2-tool-note">O Sourcebook indica que um sistema bem mantido deve perder menos de 10% da capacidade por vazamentos; sistemas mal mantidos podem chegar a 20-30%.</p><Source links={[TECH_SOURCES.doe,{label:m.sourceLabel,url:m.sourceUrl}]}/></div>
}

export function DiagnosticToolsGrid(){return <div className="v2-diagnostics-stack"><CompressorAnnualTool/><VerifiedCompressorTable/><div className="v2-diagnostic-grid"><HpKwReference/><PressureSystemTool/><CycleLeakTool/></div></div>}
