import { useMemo, useState, type ReactNode } from "react";
import { CAGI_UP6S, COPEL_A4_TARIFFS, HP_ROWS, INGERSOLL_FAMILIES, TECH_SOURCES, VERIFIED_MODELS } from "@/lib/diagnostic-data";

const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});
const fmt=(v:number,d=1)=>v.toLocaleString("pt-BR",{maximumFractionDigits:d,minimumFractionDigits:d});
const Source=({links}:{links:{label:string;url:string}[]})=><details className="v2-source"><summary>Como este diagnóstico é calculado</summary>{links.map(x=><a key={x.url} href={x.url} target="_blank" rel="noreferrer">{x.label}</a>)}</details>;
const Field=({label,children}:{label:string;children:ReactNode})=><label className="v2-diagnostic-field">{label}{children}</label>;

export function TariffReferencePanel(){
 return <div className="v2-evidence-panel"><div><span className="v2-kicker">REFERÊNCIA FINANCEIRA FIXA</span><h3>Tarifa não é um slider.</h3><p>Os cálculos de energia usam a Tarifa de Aplicação da COPEL-DIS homologada pela ANEEL para o subgrupo A4, vigência 24/06/2026 a 23/06/2027. O valor é a soma TE + TUSD de energia e serve como referência técnica comparativa, não como reprodução da fatura.</p></div><div className="v2-tariff-grid">{COPEL_A4_TARIFFS.map(x=><article key={x.id}><small>{x.label}</small><strong>R$ {fmt(x.value,5)}<i>/kWh</i></strong><span>TUSD {fmt(x.tusd,2)} + TE {fmt(x.te,2)} R$/MWh</span></article>)}</div><div className="v2-evidence-foot"><b>Não incluído:</b> demanda contratada/medida, ultrapassagem, impostos, bandeiras e demais componentes da fatura. <a href={TECH_SOURCES.copel.url} target="_blank" rel="noreferrer">Copel</a><a href={TECH_SOURCES.aneel.url} target="_blank" rel="noreferrer">Base ANEEL</a></div></div>
}

export function CompressorAnnualTool(){
 const [modelId,setModelId]=useState("up6s-30-125"),[hours,setHours]=useState(4000),[tariffId,setTariffId]=useState("a4-offpeak");
 const m=CAGI_UP6S.find(x=>x.id===modelId)??CAGI_UP6S[4],t=COPEL_A4_TARIFFS.find(x=>x.id===tariffId)??COPEL_A4_TARIFFS[0];
 const kwh=(m.packageKw??0)*hours,cost=kwh*t.value;
 return <div className="v2-diagnostic-calc v2-diagnostic-calc-featured"><div className="v2-calc-head"><div><span>01 · INGERSOLL RAND</span><h3>Consumo anual por modelo medido</h3></div><strong>{money(cost)}<small> referência anual</small></strong></div><p>Selecionamos apenas modelos que possuem ficha CAGI da Ingersoll Rand com potência total do pacote em plena carga. HP sozinho não é usado para estimar consumo.</p><div className="v2-calc-fields"><Field label="Modelo"><select value={modelId} onChange={e=>setModelId(e.target.value)}>{CAGI_UP6S.map(x=><option key={x.id} value={x.id}>{x.model}</option>)}</select></Field><Field label="Horas reais no ano"><input type="number" min="1" max="8760" value={hours} onChange={e=>setHours(Math.min(8760,Math.max(0,Number(e.target.value)||0)))}/></Field><Field label="Tarifa oficial de referência"><select value={tariffId} onChange={e=>setTariffId(e.target.value)}>{COPEL_A4_TARIFFS.map(x=><option key={x.id} value={x.id}>{x.label} · R$ {x.value.toFixed(5)}/kWh</option>)}</select></Field></div><div className="v2-result-strip"><div><small>Entrada total CAGI</small><b>{fmt(m.packageKw??0,2)} kW</b></div><div><small>Vazão medida</small><b>{fmt(m.flowCfm,0)} cfm</b></div><div><small>Energia anual</small><b>{fmt(kwh,0)} kWh</b></div><div><small>Potência específica</small><b>{fmt(m.specificKw100Cfm??0,2)} kW/100 cfm</b></div></div><Source links={[{label:m.sourceLabel,url:m.sourceUrl},TECH_SOURCES.irCagi,TECH_SOURCES.copel,TECH_SOURCES.aneel]}/></div>
}

export function VerifiedCompressorTable(){
 const [family,setFamily]=useState("Todos");const families=["Todos",...Array.from(new Set(VERIFIED_MODELS.map(x=>x.family)))];const rows=VERIFIED_MODELS.filter(x=>family==="Todos"||x.family===family);
 return <div className="v2-data-card"><div className="v2-data-card-head"><div><span className="v2-kicker">BASE DE MODELOS VERIFICADA</span><h3>Especificações que entram no site somente com fonte.</h3><p>O catálogo abaixo separa a família comercial da medição energética. Onde a fonte não publica potência total do pacote, o site não calcula custo anual.</p></div><select value={family} onChange={e=>setFamily(e.target.value)}>{families.map(x=><option key={x}>{x}</option>)}</select></div><div className="v2-family-band"><b>Famílias atuais localizadas no catálogo oficial</b><div>{INGERSOLL_FAMILIES.map((x,i)=><span key={x.name+x.range+i}>{x.name}<i>{x.range}</i></span>)}</div><p>Esta faixa é um mapa de famílias do catálogo oficial, não uma promessa de disponibilidade local. O cálculo anual abaixo só é liberado para configurações com dados CAGI de potência total.</p></div><div className="v2-tech-table-wrap"><table className="v2-tech-table"><thead><tr><th>Família</th><th>Modelo</th><th>HP</th><th>kW nominal</th><th>Pressão</th><th>FAD</th><th>Entrada pacote</th><th>Fonte</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.family}</td><td><b>{x.model}</b></td><td>{x.hp}</td><td>{x.nominalKw??"—"}</td><td>{x.pressurePsi} psi</td><td>{x.flowCfm} cfm</td><td>{x.packageKw?`${fmt(x.packageKw,2)} kW CAGI`:"não publicada nesta fonte"}</td><td><a href={x.sourceUrl} target="_blank" rel="noreferrer">abrir</a></td></tr>)}</tbody></table></div><div className="v2-evidence-foot">O catálogo oficial da Ingersoll Rand também lista linhas UP6, UP6S e Next Generation RS em faixas que vão de pequenas potências até centenas de kW. <a href="https://www.ingersollrand.com/en-us/products/air-compressors/oil-flooded-rotary-air-compressors/" target="_blank" rel="noreferrer">Catálogo oficial</a><a href="https://www.ingersollrand.com/api/air-compressor/cagi-data-sheets/contact-cooled-rotary" target="_blank" rel="noreferrer">Biblioteca CAGI</a></div></div>
}

export function HpKwReference(){return <div className="v2-diagnostic-calc"><div className="v2-calc-head"><div><span>02 · CONVERSÃO</span><h3>HP não é consumo elétrico.</h3></div></div><p>Esta tabela serve apenas para converter unidade de potência mecânica. O NIST define 1 horsepower (550 ft·lbf/s) = 745,6999 W. Um motor de 30 hp, portanto, não significa que um compressor consome exatamente 22,37 kW da rede.</p><div className="v2-mini-table">{HP_ROWS.map(x=><span key={x.hp}><b>{x.hp} hp</b><i>{fmt(x.kw,2)} kW</i></span>)}</div><Source links={[TECH_SOURCES.nist]}/></div>}

export function PressureReductionTool(){
 const [modelId,setModelId]=useState("up6s-30-125"),[current,setCurrent]=useState(8),[target,setTarget]=useState(7),[hours,setHours]=useState(4000),[tariffId,setTariffId]=useState("a4-offpeak");
 const m=CAGI_UP6S.find(x=>x.id===modelId)??CAGI_UP6S[4],t=COPEL_A4_TARIFFS.find(x=>x.id===tariffId)??COPEL_A4_TARIFFS[0];const deltaPsi=Math.max(0,current-target)*14.5038;const pct=deltaPsi/2;const savedKw=(m.packageKw??0)*(pct/100);const annual=savedKw*hours*t.value;
 return <div className="v2-diagnostic-calc"><div className="v2-calc-head"><div><span>03 · PRESSÃO</span><h3>Quanto uma redução de setpoint pode representar?</h3></div><strong>{fmt(pct,1)}%<small> triagem energética</small></strong></div><p>Regra de triagem do Compressed Air Challenge: perto de 100 psig, reduzir 2 psi na descarga reduz aproximadamente 1% do consumo em plena vazão. A curva real do fabricante prevalece.</p><div className="v2-calc-fields"><Field label="Modelo CAGI"><select value={modelId} onChange={e=>setModelId(e.target.value)}>{CAGI_UP6S.map(x=><option key={x.id} value={x.id}>{x.model}</option>)}</select></Field><Field label="Pressão atual (bar)"><input type="number" step="0.1" value={current} onChange={e=>setCurrent(Number(e.target.value)||0)}/></Field><Field label="Pressão alvo (bar)"><input type="number" step="0.1" value={target} onChange={e=>setTarget(Number(e.target.value)||0)}/></Field><Field label="Horas/ano"><input type="number" min="1" max="8760" value={hours} onChange={e=>setHours(Number(e.target.value)||0)}/></Field><Field label="Tarifa"><select value={tariffId} onChange={e=>setTariffId(e.target.value)}>{COPEL_A4_TARIFFS.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></Field></div><div className="v2-result-strip"><div><small>Redução</small><b>{fmt(deltaPsi,1)} psi</b></div><div><small>Potência evitada</small><b>{fmt(savedKw,2)} kW</b></div><div><small>Referência anual</small><b>{money(annual)}</b></div></div><p className="v2-tool-note">Triagem válida como regra de bolso em sistemas na faixa de 100 psig. Controles, demanda não regulada e comportamento em carga parcial podem alterar o resultado.</p><Source links={[{label:'Compressed Air Challenge · Sourcebook',url:'https://www.compressedairchallenge.org/'},TECH_SOURCES.doe,m.sourceUrl?{label:m.sourceLabel,url:m.sourceUrl}:TECH_SOURCES.irCagi]}/></div>
}

export function PressureDropTool(){
 const [supply,setSupply]=useState(7.5),[use,setUse]=useState(6.9);const drop=Math.max(0,supply-use),pct=supply>0?drop/supply*100:0,high=pct>=10;
 return <div className="v2-diagnostic-calc"><div className="v2-calc-head"><div><span>04 · REDE</span><h3>Queda de pressão até o ponto de uso</h3></div><strong className={high?'is-risk':''}>{fmt(pct,1)}%<small> da pressão de origem</small></strong></div><p>O DOE orienta que um sistema bem projetado tenha perda de pressão muito menor que 10% da pressão de descarga, medida da saída do reservatório ao ponto de uso.</p><div className="v2-calc-fields"><Field label="Saída do reservatório (bar)"><input type="number" step="0.1" value={supply} onChange={e=>setSupply(Number(e.target.value)||0)}/></Field><Field label="Ponto de uso (bar)"><input type="number" step="0.1" value={use} onChange={e=>setUse(Number(e.target.value)||0)}/></Field></div><div className={"v2-diagnostic-status "+(high?'risk':'ok')}><b>{high?'Acima do limite de referência':'Abaixo de 10%, mas ainda deve ser minimizada'}</b><span>Diferença medida: {fmt(drop,2)} bar. Filtros, secadores, conexões, mangueiras e tubulações são pontos típicos de investigação.</span></div><Source links={[TECH_SOURCES.doe]}/></div>
}

export function ReceiverLeakTool(){
 const [liters,setLiters]=useState(1000),[p1,setP1]=useState(7),[p2,setP2]=useState(3.5),[seconds,setSeconds]=useState(120);const ft3=liters/28.3168466,deltaPsi=Math.max(0,p1-p2)*14.5037738,minutes=Math.max(seconds/60,.0001);const cfm=(ft3*deltaPsi/(minutes*14.7))*1.25,m3min=cfm*0.0283168466;
 return <div className="v2-diagnostic-calc"><div className="v2-calc-head"><div><span>05 · VAZAMENTOS</span><h3>Teste de queda de pressão do sistema</h3></div><strong>{fmt(cfm,1)}<small> cfm estimados</small></strong></div><p>Método do DOE para períodos sem consumo produtivo: estimar o volume total pressurizado, medir P1, P2 e o tempo de queda. O cálculo converte os dados métricos para a fórmula publicada.</p><div className="v2-calc-fields"><Field label="Volume total estimado (litros)"><input type="number" min="1" value={liters} onChange={e=>setLiters(Number(e.target.value)||0)}/></Field><Field label="P1 (bar g)"><input type="number" step="0.1" value={p1} onChange={e=>setP1(Number(e.target.value)||0)}/></Field><Field label="P2 (bar g)"><input type="number" step="0.1" value={p2} onChange={e=>setP2(Number(e.target.value)||0)}/></Field><Field label="Tempo de queda (segundos)"><input type="number" min="1" value={seconds} onChange={e=>setSeconds(Number(e.target.value)||0)}/></Field></div><div className="v2-result-strip"><div><small>Vazamento estimado</small><b>{fmt(cfm,1)} cfm</b></div><div><small>Equivalente</small><b>{fmt(m3min,2)} m³/min</b></div></div><p className="v2-tool-note">O volume deve incluir reservatórios, rede e tubulação pressurizada. O DOE sugere P2 em torno de metade de P1 e ausência de demanda além dos vazamentos durante o teste.</p><Source links={[TECH_SOURCES.doe]}/></div>
}

export function CycleLeakTool(){
 const [modelId,setModelId]=useState("up6s-30-125"),[load,setLoad]=useState(1),[off,setOff]=useState(4);const m=CAGI_UP6S.find(x=>x.id===modelId)??CAGI_UP6S[4],pct=(load+off)>0?load/(load+off)*100:0,cfm=m.flowCfm*pct/100;
 return <div className="v2-diagnostic-calc"><div className="v2-calc-head"><div><span>06 · CICLO CARGA/ALÍVIO</span><h3>Percentual de capacidade perdido em vazamento</h3></div><strong className={pct>10?'is-risk':''}>{fmt(pct,1)}%<small> da capacidade</small></strong></div><p>Para compressores com controle start/stop ou carga/alívio e nenhuma demanda produtiva, o DOE publica: vazamento (%) = T carga × 100 ÷ (T carga + t alívio).</p><div className="v2-calc-fields"><Field label="Modelo / capacidade"><select value={modelId} onChange={e=>setModelId(e.target.value)}>{CAGI_UP6S.map(x=><option key={x.id} value={x.id}>{x.model} · {x.flowCfm} cfm</option>)}</select></Field><Field label="Tempo em carga (min)"><input type="number" step="0.1" min="0" value={load} onChange={e=>setLoad(Number(e.target.value)||0)}/></Field><Field label="Tempo aliviado/desligado (min)"><input type="number" step="0.1" min="0" value={off} onChange={e=>setOff(Number(e.target.value)||0)}/></Field></div><div className="v2-result-strip"><div><small>Capacidade publicada</small><b>{m.flowCfm} cfm</b></div><div><small>Vazamento equivalente</small><b>{fmt(cfm,1)} cfm</b></div><div><small>Benchmark DOE</small><b>&lt;10%</b></div></div><p className="v2-tool-note">O Sourcebook indica que um sistema bem mantido deve perder menos de 10% da capacidade por vazamentos; sistemas mal mantidos podem chegar a 20-30%.</p><Source links={[TECH_SOURCES.doe,{label:m.sourceLabel,url:m.sourceUrl}]}/></div>
}

export function HeatRecoveryTool(){
 const [modelId,setModelId]=useState("up6s-30-125");const m=CAGI_UP6S.find(x=>x.id===modelId)??CAGI_UP6S[4],p=m.packageKw??0;const heatLow=p*.80,heatHigh=p*.93,recoverLow=heatLow*.50,recoverHigh=heatHigh*.90;
 return <div className="v2-diagnostic-calc"><div className="v2-calc-head"><div><span>07 · CALOR REJEITADO</span><h3>Potencial técnico de recuperação de calor</h3></div></div><p>O DOE informa que 80-93% da energia elétrica de um compressor industrial vira calor e que um sistema de recuperação bem projetado pode recuperar 50-90% desse calor disponível.</p><div className="v2-calc-fields"><Field label="Modelo CAGI"><select value={modelId} onChange={e=>setModelId(e.target.value)}>{CAGI_UP6S.map(x=><option key={x.id} value={x.id}>{x.model} · {fmt(x.packageKw??0,2)} kW pacote</option>)}</select></Field></div><div className="v2-result-strip"><div><small>Calor gerado</small><b>{fmt(heatLow,1)}-{fmt(heatHigh,1)} kW térmicos</b></div><div><small>Faixa recuperável</small><b>{fmt(recoverLow,1)}-{fmt(recoverHigh,1)} kW térmicos</b></div></div><p className="v2-tool-note">É um potencial térmico, não uma promessa de economia financeira. A utilidade depende de aplicação, temperaturas, horas simultâneas e projeto do recuperador.</p><Source links={[TECH_SOURCES.doe,{label:m.sourceLabel,url:m.sourceUrl}]}/></div>
}

export function DiagnosticToolsGrid(){return <div className="v2-diagnostics-stack"><CompressorAnnualTool/><VerifiedCompressorTable/><div className="v2-diagnostic-grid"><HpKwReference/><PressureReductionTool/><PressureDropTool/><ReceiverLeakTool/><CycleLeakTool/><HeatRecoveryTool/></div></div>}
