import { createFileRoute, Link } from "@tanstack/react-router";
import { PageFrame, PageHero, SectionHead, ContactBand, VideoEmbed } from "@/components/site-v2";
import { CommunityGallery } from "@/components/community-gallery";
import { pageMeta } from "@/lib/page-meta";
export const Route=createFileRoute("/empresa")({head:()=>pageMeta("/empresa","Empresa | TecAr Compressores","Conheça a TecAr Compressores, sua trajetória desde 1999, o Instituto Luiz Gonzaga e as ações sociais realizadas pela empresa.","/assets/v2/tecar-service.png"),component:Page});
function Page(){return <PageFrame>
<PageHero kicker="A TECAR" title="Experiência técnica construída desde 1999." text="A TecAr atua com soluções para ar comprimido, reunindo equipamentos, assistência, engenharia, locação e tecnologia para atender a indústria." image="/assets/unique/generated/company-hero.webp"><a href="https://wa.me/5541996441330?text=Ol%C3%A1%2C%20vim%20pelo%20site%20da%20TecAr." target="_blank" rel="noopener noreferrer" className="v2-primary">Falar com a TecAr</a></PageHero>
<section className="v2-section"><div className="v2-container v2-company-intro"><SectionHead title="Compressores e competência." text="A empresa é assistência técnica e revendedora autorizada Ingersoll Rand desde 1999. A equipe técnica recebe capacitação e atualização para acompanhar equipamentos, ferramentas de diagnóstico e novas tecnologias."/><div className="v2-stat-blocks"><div><strong>1999</strong><span>início da atuação</span></div><div><strong>500+</strong><span>clientes atendidos</span></div><div><strong>2</strong><span>unidades operacionais</span></div></div></div></section>
<section className="v2-section v2-soft"><div className="v2-container"><SectionHead title="Missão, visão e valores"/><div className="v2-value-grid"><article><h3>Missão</h3><p>Oferecer soluções confiáveis em ar comprimido com orientação técnica, suporte contínuo e foco na operação do cliente.</p></article><article><h3>Visão</h3><p>Ser reconhecida pela capacidade técnica, proximidade e evolução constante das soluções de ar comprimido.</p></article><article><h3>Valores</h3><p>Ética, segurança, qualidade técnica, responsabilidade, melhoria contínua e compromisso com o cliente.</p></article><article><h3>Responsabilidade</h3><p>O Instituto Luiz Gonzaga e as ações mensais da TecAr conectam a empresa à sociedade e ao meio ambiente.</p></article></div></div></section>
<section className="v2-social-impact" id="instituto"><div className="v2-container">
<div className="v2-social-impact-head"><div><span className="v2-kicker">NOSSA PRESENÇA NA COMUNIDADE</span><h2>Instituto Luiz Gonzaga</h2></div><p>Cuidar das pessoas também faz parte da nossa atuação. Por meio do Instituto Luiz Gonzaga, a TecAr participa de ações solidárias que aproximam nossa equipe das comunidades e transformam apoio em presença.</p></div>
<div className="tc-community-stories"><article><h3>Um Natal mais próximo</h3><p>Entregamos presentes de Natal para crianças de comunidades ribeirinhas de Paranaguá. É uma oportunidade de compartilhar alegria e fortalecer os vínculos com as famílias da região.</p></article><article><h3>Cuidado em todas as idades</h3><p>Apoiamos lares de idosos e participamos de iniciativas de acolhimento e convivência. Doações, visitas e atenção fazem parte desse compromisso com as pessoas.</p></article><article><h3>Uma equipe que participa</h3><p>Ações de Páscoa, campanhas como o Agosto Lilás e outras iniciativas mobilizam nossa equipe em torno da solidariedade e do cuidado com a comunidade.</p></article></div>
<CommunityGallery/>
</div></section>
<section className="v2-section tc-awards" id="premios"><div className="v2-container"><div className="tc-awards-heading"><SectionHead kicker="RECONHECIMENTO" title="Competência reconhecida. Compromisso renovado." text="Os reconhecimentos recebidos pela TecAr refletem o trabalho da equipe em vendas, capacitação e pós-venda. Para nossos clientes, representam uma trajetória de dedicação ao atendimento e à construção de soluções de valor."/></div><figure className="tc-awards-photo"><img src="/assets/community/premios-tecar.png" width="665" height="405" loading="lazy" alt="Troféus e reconhecimentos da TecAr expostos junto às marcas TecAr e Ingersoll Rand"/><figcaption>Reconhecimentos que fazem parte da história da TecAr.</figcaption></figure><div className="tc-awards-list">
<article><span>2017</span><h3>Destaque de vendas</h3><p>Segmento comercial e premium</p></article>
<article><span>2017</span><h3>Destaque de vendas</h3><p>Contact Cooled</p></article><article><span>2022</span><h3>Melhor performance pós-venda</h3></article>
<article><span>2023</span><h3>Destaque no treinamento de vendas</h3></article>
<article><span>2023</span><h3>Melhor venda de valor</h3></article>
<article><span>2023</span><h3>Melhor performance geral</h3></article>
<article><span>PROCESSOS COMERCIAIS</span><h3>Melhores práticas do Salesforce</h3></article>
</div></div></section>
<section className="v2-section"><div className="v2-container"><SectionHead kicker="COMPETÊNCIA" title="O que sustenta o atendimento"/><div className="v2-timeline"><div><b>Experiência</b><p>Atuação contínua no mercado industrial desde 1999.</p></div><div><b>Autorização</b><p>Assistência técnica e revenda autorizada Ingersoll Rand.</p></div><div><b>Capacitação</b><p>Técnicos certificados e atualizações recorrentes de diagnóstico e tecnologia.</p></div><div><b>Presença</b><p>Estrutura em Curitiba e Paranaguá para aproximar o suporte do cliente.</p></div><div><b>Pós-vendas</b><p>Histórico de reconhecimento da operação de pós-vendas da TecAr.</p></div></div></div></section>
<section className="v2-section v2-video-section"><div className="v2-container"><SectionHead title="Veja a TecAr em vídeo"/><div className="v2-video-grid"><VideoEmbed id="vSjkXQut3jQ" title="Institucional TecAr"/><VideoEmbed id="clxX-mMdwYQ" title="Motores HPM"/></div></div></section>
<section className="v2-units"><div className="v2-container"><SectionHead title="Duas unidades, uma operação integrada."/><div className="v2-unit-grid"><article><h3>Curitiba</h3><p>R. das Carmelitas, 1935, Boqueirão, Curitiba PR</p><a href="tel:+554133769966">(41) 3376-9966</a><a href="mailto:tecarindustrial@tecarcompressores.com.br">tecarindustrial@tecarcompressores.com.br</a></article><article><h3>Paranaguá</h3><p>R. Prof. Décio, 197, Rocio, Paranaguá PR</p><a href="tel:+554134227855">(41) 3422-7855</a><a href="mailto:tecarportuaria@tecarcompressores.com.br">tecarportuaria@tecarcompressores.com.br</a></article></div></div></section>
<ContactBand/></PageFrame>}
