import { createFileRoute, Link } from "@tanstack/react-router";
import { PageFrame, PageHero, SectionHead, ContactBand, VideoEmbed } from "@/components/site-v2";
import { pageMeta } from "@/lib/page-meta";
export const Route=createFileRoute("/empresa")({head:()=>pageMeta("/empresa","Empresa | TecAr Compressores","Conheça a TecAr Compressores, assistência e revenda autorizada Ingersoll Rand desde 1999 em Curitiba e Paranaguá.","/assets/v2/tecar-service.png"),component:Page});
function Page(){return <PageFrame>
<PageHero kicker="A TECAR" title="Experiência técnica construída desde 1999." text="A TecAr atua com soluções para ar comprimido, reunindo equipamentos, assistência, engenharia, locação e tecnologia para atender a indústria." image="/assets/v2/tecar-service.png"><Link to="/contato" className="v2-primary">Falar com a TecAr</Link></PageHero>
<section className="v2-section"><div className="v2-container v2-company-intro"><SectionHead title="Compressores e competência." text="A empresa é assistência técnica e revendedora autorizada Ingersoll Rand desde 1999. A equipe técnica recebe capacitação e atualização para acompanhar equipamentos, ferramentas de diagnóstico e novas tecnologias."/><div className="v2-stat-blocks"><div><strong>1999</strong><span>início da atuação</span></div><div><strong>500+</strong><span>clientes atendidos</span></div><div><strong>2</strong><span>unidades operacionais</span></div></div></div></section>
<section className="v2-section v2-soft"><div className="v2-container"><SectionHead title="Missão, visão e valores"/><div className="v2-value-grid"><article><h3>Missão</h3><p>Oferecer soluções confiáveis em ar comprimido com orientação técnica, suporte contínuo e foco na operação do cliente.</p></article><article><h3>Visão</h3><p>Ser reconhecida pela capacidade técnica, proximidade e evolução constante das soluções de ar comprimido.</p></article><article><h3>Valores</h3><p>Ética, segurança, qualidade técnica, responsabilidade, melhoria contínua e compromisso com o cliente.</p></article><article><h3>Responsabilidade</h3><p>A TecAr mantém ações sociais e compromissos institucionais que fazem parte da história apresentada pela empresa.</p></article></div></div></section>
<section className="v2-section"><div className="v2-container"><SectionHead kicker="COMPETÊNCIA" title="O que sustenta o atendimento"/><div className="v2-timeline"><div><b>Experiência</b><p>Atuação contínua no mercado industrial desde 1999.</p></div><div><b>Autorização</b><p>Assistência técnica e revenda autorizada Ingersoll Rand.</p></div><div><b>Capacitação</b><p>Técnicos certificados e atualizações recorrentes de diagnóstico e tecnologia.</p></div><div><b>Presença</b><p>Estrutura em Curitiba e Paranaguá para aproximar o suporte do cliente.</p></div><div><b>Pós-vendas</b><p>Histórico de reconhecimento da operação de pós-vendas da TecAr.</p></div></div></div></section>
<section className="v2-section v2-video-section"><div className="v2-container"><SectionHead title="Veja a TecAr em vídeo"/><div className="v2-video-grid"><VideoEmbed id="vSjkXQut3jQ" title="Institucional TecAr"/><VideoEmbed id="clxX-mMdwYQ" title="Motores HPM"/></div></div></section>
<section className="v2-units"><div className="v2-container"><SectionHead title="Duas unidades, uma operação integrada."/><div className="v2-unit-grid"><article><h3>Curitiba</h3><p>R. das Carmelitas, 1935, Boqueirão, Curitiba PR</p><a href="tel:+554133769966">(41) 3376-9966</a><a href="mailto:tecarindustrial@tecarcompressores.com.br">tecarindustrial@tecarcompressores.com.br</a></article><article><h3>Paranaguá</h3><p>R. Prof. Décio, 197, Rocio, Paranaguá PR</p><a href="tel:+554134227855">(41) 3422-7855</a><a href="mailto:tecarportuaria@tecarcompressores.com.br">tecarportuaria@tecarcompressores.com.br</a></article></div></div></section>
<ContactBand/></PageFrame>}
