import { createFileRoute, Link } from "@tanstack/react-router";
import { PageFrame, PageHero, SectionHead, ContactBand } from "@/components/site-v2";
import { EnergyLossTool } from "@/components/client-tools";
import { pageMeta } from "@/lib/page-meta";
export const Route=createFileRoute("/engenharia")({head:()=>pageMeta("/engenharia","Engenharia de Ar Comprimido | TecAr","Eficiência energética, auditoria de sistemas, projeto de redes de ar e casa de máquinas para melhorar desempenho e reduzir perdas.","/assets/v2/tecar-engineering.png"),component:Page});
const areas=[["Eficiência energética","Medições e estudos para entender como a energia elétrica está sendo convertida em energia pneumática útil."],["Diagnóstico e auditoria","Análise do sistema para identificar vazamentos, desperdícios, gargalos e oportunidades de melhoria."],["Projetos de ar comprimido","Dimensionamento do sistema de acordo com demanda, estabilidade operacional e requisitos do processo."],["Projeto de rede","Cálculo de diâmetro, velocidade e perda de carga para distribuir o ar de forma adequada."],["Casa de máquinas","Projeto de espaço, ventilação, acesso e condições de instalação para preservar o equipamento."]];
function Page(){return <PageFrame>
<PageHero kicker="ENGENHARIA" title="Ar comprimido deve ser dimensionado, medido e otimizado." text="A equipe de engenharia da TecAr trabalha com confiabilidade, eficiência e economia para melhorar a geração e a distribuição do ar comprimido." image="/assets/v2/tecar-engineering.png"><Link to="/contato" className="v2-primary">Solicitar diagnóstico</Link></PageHero>
<section className="v2-section"><div className="v2-container"><SectionHead title="Engenharia aplicada ao sistema completo"/><div className="v2-engineering-list">{areas.map(([t,d],i)=><article key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>
<section className="v2-section v2-soft"><div className="v2-container v2-two-col"><div><SectionHead kicker="PERDAS" title="Transforme desperdício em número." text="Vazamento, queda de pressão e operação fora do ponto ideal podem elevar o consumo sem entregar mais produção. Use o simulador como referência inicial e confirme com medição de campo."/><div className="v2-factbox"><strong>20% a 30%</strong><span>é a faixa de desperdício por vazamentos citada no conteúdo técnico da própria TecAr para muitas instalações industriais.</span></div></div><EnergyLossTool/></div></section>
<section className="v2-section"><div className="v2-container v2-image-copy"><img src="/assets/v2/lines.jpg" alt="Rede industrial de ar comprimido"/><div><SectionHead title="A rede também faz parte da eficiência." text="Tubulação subdimensionada, trajetos inadequados e perdas de carga podem comprometer pressão, consumo e estabilidade. O projeto precisa considerar a demanda real do processo."/><Link to="/linhas-de-ar" className="v2-secondary">Conhecer linhas de ar</Link></div></div></section>
<ContactBand/></PageFrame>}
