import { createFileRoute, Link } from "@tanstack/react-router";
import { PageFrame, PageHero, ContactBand } from "@/components/site-v2";
import { AirLineExplorer } from "@/components/air-line-explorer";
import { pageMeta } from "@/lib/page-meta";

export const Route=createFileRoute("/linhas-de-ar")({head:()=>pageMeta("/linhas-de-ar","Linhas de Ar Comprimido | TecAr","Rede em alumínio organizada por etapas de projeto e distribuição.","https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=1920,fit=crop/YZ9EgGEK8zh4Pjl4/piping-application-6-1200x800-1-mePg6NWzlRFonDzk.jpg"),component:Page});

function Page(){return <PageFrame>
 <PageHero kicker="LINHAS DE AR" title="Veja como a rede é organizada." text="Clique em cada etapa da distribuição e entenda o papel dela no sistema." image="/assets/unique/generated/distribution-hero.webp"><a href="https://wa.me/5541996441330?text=Ol%C3%A1%2C%20vim%20pelo%20site%20da%20TecAr." target="_blank" rel="noopener noreferrer" className="v2-primary">Projetar rede</a></PageHero>
 <section className="v2-section"><div className="v2-container"><AirLineExplorer/></div></section>
<section className="v2-section v2-soft"><div className="v2-container"><div className="v2-sectionhead"><h2>Escolha a rede pelo resultado na operação.</h2></div><div className="tc-benefits"><article><h3>SimplAir em alumínio</h3><p>Tubos leves, resistência à corrosão e conexões que facilitam alterações de layout. A superfície interna favorece o escoamento e ajuda a limitar perdas de pressão.</p></article><article><h3>PPR para ar comprimido</h3><p>Quando homologado pelo fabricante para ar comprimido, oferece resistência à corrosão e uniões por termofusão. A escolha exige verificar pressão, temperatura, fluido e condições de instalação.</p></article><article><h3>Material e projeto trabalhando juntos</h3><p>Em alumínio, PPR adequado ou outra solução especificada, dimensionamento e montagem fazem a diferença. Uma rede bem projetada facilita manutenção, expansão e controle de vazamentos.</p></article></div><p className="tc-benefits-note">A TecAr compara materiais, diâmetros e traçado conforme a sua demanda. O objetivo é entregar pressão no ponto de uso com menor perda e um custo de operação consistente.</p></div></section> <ContactBand title="Sua rede acompanha o crescimento da produção?" text="Conte quais setores precisam de ar, a pressão de trabalho e os planos de expansão. Vamos avaliar o melhor caminho."/>
</PageFrame>}
