import { createFileRoute, Link } from "@tanstack/react-router";
import { PageFrame, PageHero, SectionHead, ContactBand } from "@/components/site-v2";
import { pageMeta } from "@/lib/page-meta";
export const Route=createFileRoute("/locacao")({head:()=>pageMeta("/locacao","Locação de Compressores | TecAr","Locação emergencial e contratos de longo prazo para compressores, secadores e reservatórios de ar comprimido.","/assets/v2/rental.png"),component:Page});
function Page(){return <PageFrame>
<PageHero kicker="LOCAÇÃO" title="Geração de ar com flexibilidade operacional." text="A TecAr oferece locação de compressores, secadores e reservatórios para necessidades emergenciais e contratos de longo prazo, inclusive no modelo de venda de ar." image="/assets/unique/generated/rental-hero.webp"><a href="https://wa.me/5541996441330?text=Ol%C3%A1%2C%20vim%20pelo%20site%20da%20TecAr." target="_blank" rel="noopener noreferrer" className="v2-primary">Consultar disponibilidade</a></PageHero>
<section className="v2-section"><div className="v2-container"><SectionHead title="Quando a locação faz sentido"/><div className="v2-feature-row"><article><h3>Emergência</h3><p>Suporte para situações em que a geração de ar precisa ser restabelecida sem esperar uma aquisição definitiva.</p></article><article><h3>Longo prazo</h3><p>Contratos a partir de um ano para transformar parte do investimento em custo operacional previsível.</p></article><article><h3>Venda de ar</h3><p>Modelo em que a necessidade de geração é tratada como serviço, com foco na disponibilidade do sistema.</p></article></div></div></section>
<section className="v2-section v2-soft"><div className="v2-container v2-rental-flow"><div><SectionHead kicker="PROCESSO" title="Do levantamento à operação"/><p>A escolha depende de vazão, pressão, qualidade do ar, regime de trabalho, espaço disponível e criticidade do processo.</p></div><div className="v2-step-strip"><span>Demanda</span><i/> <span>Dimensionamento</span><i/> <span>Instalação</span><i/> <span>Operação</span><i/> <span>Suporte</span></div></div></section>
<section className="v2-section"><div className="v2-container"><SectionHead title="Equipamentos disponíveis para locação" text="A disponibilidade varia conforme potência, pressão e configuração. Consulte a equipe para dimensionar o conjunto adequado."/><div className="v2-rental-products"><img src="/assets/unique/official/rental-a.webp" alt="Compressor industrial disponível no catálogo de locação TecAr"/><img src="/assets/unique/official/rental-compressor.webp" alt="Compressor de pistão do catálogo de locação TecAr"/><img src="/assets/unique/official/rental-b.webp" alt="Conjunto industrial de compressão do catálogo TecAr"/></div></div></section>
<ContactBand title="Precisa de ar comprimido sem esperar uma compra?" text="Informe pressão, vazão aproximada, período de uso e local da instalação para agilizar o dimensionamento."/></PageFrame>}
