import { createFileRoute, Link } from "@tanstack/react-router";
import { PageFrame, PageHero, SectionHead, ContactBand } from "@/components/site-v2";
import { DowntimeTool } from "@/components/client-tools";
import { pageMeta } from "@/lib/page-meta";
export const Route=createFileRoute("/manutencao")({head:()=>pageMeta("/manutencao","Manutenção de Compressores | TecAr","Assistência técnica multimarcas, manutenção preventiva, corretiva, diagnóstico e suporte NR13 para sistemas de ar comprimido.","/assets/v2/tecar-service.png"),component:Page});
function Page(){return <PageFrame>
<PageHero kicker="MANUTENÇÃO" title="Menos improviso. Mais previsibilidade." text="Assistência técnica multimarcas, manutenção preventiva, corretiva e ferramentas de diagnóstico para reduzir tempo de parada e aumentar a assertividade do atendimento." image="/assets/v2/tecar-service.png"><Link to="/contato" className="v2-primary">Solicitar atendimento</Link></PageHero>
<section className="v2-section"><div className="v2-container"><SectionHead title="Assistência técnica multimarcas" text="Planejamento, comunicação com o cliente e diagnóstico formam a base do atendimento. A manutenção deve preservar disponibilidade, não apenas reagir quando o equipamento para."/><div className="v2-feature-row"><article><h3>Preventiva</h3><p>Programação de intervenções conforme condição, carga horária e necessidade do equipamento.</p></article><article><h3>Corretiva</h3><p>Diagnóstico técnico e intervenção para restabelecer a operação com clareza sobre a causa da falha.</p></article><article><h3>Diagnóstico</h3><p>Uso de ferramentas e medições para aumentar a precisão antes da substituição de componentes.</p></article></div></div></section>
<section className="v2-section v2-soft"><div className="v2-container v2-two-col"><div><SectionHead kicker="GESTÃO PREVENTIVA" title="O histórico precisa trabalhar a favor da manutenção." text="A TecAr organiza a programação e o acompanhamento das intervenções para antecipar necessidades e reduzir o risco de corretivas provocadas por falta de manutenção."/><ol className="v2-process-list"><li><b>1</b><span>Identificação do equipamento e histórico</span></li><li><b>2</b><span>Planejamento da preventiva</span></li><li><b>3</b><span>Execução e registro técnico</span></li><li><b>4</b><span>Acompanhamento da próxima necessidade</span></li></ol></div><DowntimeTool/></div></section>
<section className="v2-section"><div className="v2-container v2-nr-grid"><img src="/assets/v2/tecar-service.png" alt="Técnico em manutenção de compressor"/><div><SectionHead kicker="NR13" title="Reservatórios e vasos de pressão exigem atenção técnica." text="A NR13 estabelece requisitos para inspeção e segurança de vasos de pressão. Quando aplicável ao sistema de ar comprimido, a TecAr orienta o cliente sobre a necessidade de inspeção por profissional habilitado."/><Link to="/contato" className="v2-secondary">Consultar NR13</Link></div></div></section>
<ContactBand title="Seu compressor precisa de atendimento?" text="Envie o contexto da máquina, sintomas e urgência. A equipe TecAr direciona o atendimento adequado."/></PageFrame>}
