import { createFileRoute, Link } from "@tanstack/react-router";
import { PageFrame, PageHero, SectionHead, ContactBand } from "@/components/site-v2";
import { MonitoringDemo } from "@/components/client-tools";
import { pageMeta } from "@/lib/page-meta";
export const Route=createFileRoute("/tecar-connect")({head:()=>pageMeta("/tecar-connect","TecAr Connect | Monitoramento Remoto","Monitoramento remoto de compressores com acompanhamento de variáveis, alarmes e histórico para apoiar disponibilidade e eficiência.","/assets/v2/tecar-connect.png"),component:Page});
const tracked=[["Temperatura","Acompanhe tendências e sinais de aquecimento anormal."],["Pressão","Visualize comportamento do sistema e variações operacionais."],["Ponto de orvalho","Apoie o controle da qualidade do ar e da umidade."],["Energia","Observe consumo e comportamento energético do conjunto."],["Carga e alívio","Entenda como o compressor trabalha ao longo do tempo."],["Alarmes","Receba contexto mais cedo para agir antes de uma parada maior."]];
function Page(){return <PageFrame>
<PageHero kicker="TECAR CONNECT" title="O compressor na palma da mão." text="Monitoramento remoto para acompanhar condições físicas e operacionais do equipamento, com visualização gráfica, parâmetros e alarmes." image="/assets/v2/tecar-connect.png"><a href="https://wa.me/5541996441330?text=Ol%C3%A1%2C%20vim%20pelo%20site%20da%20TecAr." target="_blank" rel="noopener noreferrer" className="v2-primary">Quero monitorar</a></PageHero>
<section className="v2-section"><div className="v2-container v2-two-col"><div><SectionHead title="Da reação para a observação contínua." text="Na operação da TecAr, soluções como o TUDO REMOTO ampliam a visibilidade sobre o compressor. O objetivo é perceber tendência, desvio e necessidade de intervenção com mais contexto."/> <div className="v2-feature-list">{tracked.map(([t,d])=><div key={t}><b>{t}</b><span>{d}</span></div>)}</div></div><MonitoringDemo/></div></section>
<section className="v2-section v2-soft"><div className="v2-container"><SectionHead kicker="COMO AJUDA" title="Informação útil para manutenção e operação"/><div className="v2-benefit-grid"><article><strong>01</strong><h3>Histórico</h3><p>Compare o comportamento atual com períodos anteriores e intervenções realizadas.</p></article><article><strong>02</strong><h3>Alertas</h3><p>Sinais de anomalia ganham visibilidade sem depender apenas da inspeção presencial.</p></article><article><strong>03</strong><h3>Eficiência</h3><p>Consumo e regime de trabalho podem indicar oportunidades de ajuste e investigação.</p></article><article><strong>04</strong><h3>Planejamento</h3><p>Dados ajudam a preparar a próxima visita com mais contexto sobre o equipamento.</p></article></div></div></section>
<section className="v2-section"><div className="v2-container v2-monitor-diagram"><div><SectionHead title="Do sensor à decisão"/><p>O monitoramento não substitui a assistência técnica. Ele cria uma camada de observação que ajuda a priorizar e interpretar o que acontece na máquina.</p></div><div className="v2-flow-graphic"><span>Equipamento</span><i>→</i><span>Sensores</span><i>→</i><span>Dados</span><i>→</i><span>Análise</span><i>→</i><span>Ação técnica</span></div></div></section>
<ContactBand title="Quer entender o que pode ser monitorado no seu equipamento?" text="Informe modelo, aplicação e configuração atual. A equipe TecAr verifica a solução compatível."/></PageFrame>}
